version: '3.4'

services:
  cogtiler:
    build:
      context: .
      dockerfile: Dockerfile
      target: production

    ports:
      - 8000:8000
    command: python -m uvicorn main:app --host 0.0.0.0  --port 8000
